# Generated by Django 4.1.7 on 2023-03-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppConsultorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='profesional',
            name='especialidades',
            field=models.ManyToManyField(to='AppConsultorio.especialidad'),
        ),
    ]
